version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: /home/circleci/project
    steps:
      - checkout
      - restore_cache:
          name: Restore .npm cache
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
          environment:
            - npm_config_cache: /home/circleci/project/npm_cache
      - save_cache:
          name: Save .npm cache
          paths: npm_cache
          key: npm-{{ checksum "package.json" }}
      - run: 
          name: Do a production build
          command: npm run build
