name: ci
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    name: Test production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Do a production build
        run: |
          npm ci
          npm run build
  audit:
    name: Dependency vulnerability audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Check for dependency vulnerabilities
        run: |
          npm ci
          npm audit
